# Generated by Django 5.0.1 on 2024-05-13 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Keywords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kljucne_rijeci', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Tenders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis', models.TextField()),
                ('status', models.TextField()),
                ('datum_objave', models.TextField()),
                ('sifra', models.TextField()),
            ],
        ),
    ]
