# Generated by Django 5.0.1 on 2024-05-13 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keywords',
            name='kljucne_rijeci',
            field=models.TextField(),
        ),
    ]
